<#
.SYNOPSIS
    Downloads human game databases for evaluation tuning.

.DESCRIPTION
    Fetches monthly archives from the Lichess Elite database, which is the
    standard Lichess dump filtered to games where both players are rated 2200+
    and the winner 2300+. Every game is a real game between strong humans.

    WHY HUMAN GAMES. The weights being fitted are fitted against the result of
    the game the position came from. Engine self-play would give cleaner labels,
    but they would be cleaner in a way that does not help: the games would be
    generated by the very evaluation being replaced, so positions it misjudges
    are exactly the positions the data would never visit, and weaknesses
    neither side can punish would be labelled as costing nothing. Human blunders
    are noise, and noise averages out over millions of positions. A blind spot
    shared by both players does not.

    LICENSING. Lichess publishes these games under CC0. Positions and results
    are facts about games that were played; nothing here is derived from another
    engine's evaluation, which is the thing that would actually be encumbered.

.PARAMETER Months
    How many monthly archives to fetch, working backwards from -From.

.PARAMETER From
    Latest month to fetch, "YYYY-MM". Defaults to the newest one published.

.PARAMETER Dest
    Where to put them. Defaults to external\training (gitignored).

.PARAMETER KeepZip
    Keep the .zip archives after extracting. Off by default - they are 76 MB
    each and re-downloading is cheaper than storing them.

.PARAMETER Parallel
    How many archives to download at once. The server throttles each connection
    to roughly 120 KB/s but does not appear to cap the total, so concurrency is
    close to a linear speedup and the difference between a twenty-minute fetch
    and a two-hour one. Be polite about the number.

.EXAMPLE
    powershell tools\fetch-training-data.ps1
    powershell tools\fetch-training-data.ps1 -Months 12 -From 2025-06
#>
[CmdletBinding()]
param(
    [int]    $Months   = 8,
    [string] $From     = '',
    [string] $Dest     = '',
    [int]    $Parallel = 5,
    [switch] $KeepZip
)

. "$PSScriptRoot\common.ps1"
$ErrorActionPreference = 'Stop'
$ProgressPreference    = 'SilentlyContinue'   # Invoke-WebRequest is ~10x slower with it

$BaseUrl = 'https://database.nikonoel.fr'

# .NET Framework caps outbound connections at TWO per host, so -Parallel above
# that silently does nothing: the extra downloads sit at zero bytes waiting for
# a slot. PowerShell 5.1 is .NET Framework, so this line is what actually makes
# concurrency work.
[System.Net.ServicePointManager]::DefaultConnectionLimit = 32
[System.Net.ServicePointManager]::SecurityProtocol = [System.Net.SecurityProtocolType]::Tls12

if (-not $Dest) { $Dest = Join-Path $ExternalDir 'training' }
Ensure-Dir $Dest | Out-Null

# ------------------------------------------------------ which months exist ---

Write-Section 'Lichess Elite database'

$index     = Invoke-WebRequest -Uri "$BaseUrl/" -UseBasicParsing
$available = @([regex]::Matches($index.Content, 'lichess_elite_(\d{4}-\d{2})\.zip') |
                ForEach-Object { $_.Groups[1].Value } | Sort-Object -Unique -Descending)

if ($available.Count -eq 0) {
    Write-Fail "Could not read the archive index at $BaseUrl"
    exit 1
}
Write-Host ("  {0} monthly archives published, newest {1}" -f $available.Count, $available[0])

if ($From) {
    $start = [array]::IndexOf($available, $From)
    if ($start -lt 0) {
        Write-Fail "No archive for $From. Newest is $($available[0]), oldest $($available[-1])."
        exit 1
    }
} else {
    $start = 0
}

$wanted = @($available[$start..([Math]::Min($start + $Months - 1, $available.Count - 1))])
Write-Host ("  fetching {0}: {1} .. {2}" -f $wanted.Count, $wanted[0], $wanted[-1])
Write-Host ("  destination {0}" -f $Dest)

# ------------------------------------------------------------- download ------

$total   = 0
$todo    = @()

foreach ($m in $wanted) {
    $pgn = Join-Path $Dest "lichess_elite_$m.pgn"
    if (Test-Path $pgn) {
        Write-Ok ("{0} already present ({1} MB)" -f $m, [Math]::Round((Get-Item $pgn).Length / 1MB))
        $total += (Get-Item $pgn).Length
    } else {
        $todo += $m
    }
}

# Download in batches, then unzip each batch. Unzipping is CPU-bound and the
# download is not, so overlapping them buys nothing worth the complexity.
for ($i = 0; $i -lt $todo.Count; $i += $Parallel) {
    $batch = @($todo[$i..([Math]::Min($i + $Parallel - 1, $todo.Count - 1))])

    Write-Host ("  downloading {0} concurrently: {1}" -f $batch.Count, ($batch -join ', '))
    $sw      = [Diagnostics.Stopwatch]::StartNew()
    $pending = @()

    foreach ($m in $batch) {
        $wc = New-Object System.Net.WebClient
        $pending += [pscustomobject]@{
            Month  = $m
            Client = $wc
            Zip    = (Join-Path $Dest "lichess_elite_$m.zip")
            Task   = $wc.DownloadFileTaskAsync("$BaseUrl/lichess_elite_$m.zip",
                                               (Join-Path $Dest "lichess_elite_$m.zip"))
        }
    }

    try {
        [System.Threading.Tasks.Task]::WaitAll(@($pending | ForEach-Object { $_.Task }))
    } catch {
        Write-Warn2 "at least one download in this batch failed: $($_.Exception.Message)"
    }
    $sw.Stop()

    $batchBytes = 0
    foreach ($d in $pending) {
        $d.Client.Dispose()
        if (Test-Path $d.Zip) { $batchBytes += (Get-Item $d.Zip).Length }
    }
    Write-Host ("    {0} MB in {1:N0}s ({2:N0} KB/s aggregate)" -f
                [Math]::Round($batchBytes / 1MB), $sw.Elapsed.TotalSeconds,
                ($batchBytes / 1KB / [Math]::Max($sw.Elapsed.TotalSeconds, 1)))

    foreach ($d in $pending) {
        if (-not (Test-Path $d.Zip)) {
            Write-Fail "download failed for $($d.Month)"
            continue
        }

        $pgn     = Join-Path $Dest ("lichess_elite_{0}.pgn" -f $d.Month)
        $staging = Join-Path $Dest ("_unzip_{0}" -f $d.Month)
        if (Test-Path $staging) { Remove-Item $staging -Recurse -Force }

        try {
            Expand-Archive -Path $d.Zip -DestinationPath $staging -Force
        } catch {
            Write-Fail "$($d.Month): archive is corrupt, skipping"
            Remove-Item $d.Zip -Force -ErrorAction SilentlyContinue
            continue
        }

        $inner = @(Get-ChildItem $staging -Recurse -Filter *.pgn)
        if ($inner.Count -eq 0) {
            Write-Fail "no .pgn inside lichess_elite_$($d.Month).zip"
        } else {
            Move-Item $inner[0].FullName $pgn -Force
            $total += (Get-Item $pgn).Length
            Write-Ok ("{0}: {1} MB of PGN" -f $d.Month, [Math]::Round((Get-Item $pgn).Length / 1MB))
        }

        Remove-Item $staging -Recurse -Force
        if (-not $KeepZip) { Remove-Item $d.Zip -Force -ErrorAction SilentlyContinue }
    }
}

Write-Section 'Done'
Write-Host ("  {0} PGN files, {1:N1} GB total" -f
            (Get-ChildItem $Dest -Filter *.pgn).Count, ($total / 1GB))
Write-Host ''
Write-Host '  Next: turn the games into labelled positions, then fit.' -ForegroundColor Cyan
Write-Host '    make tuner'
Write-Host ("    .\tuner.exe extract {0}\*.pgn -o {0}\human.epd -minply 12 -stride 6" -f $Dest)
Write-Host ("    .\tuner.exe tune {0}\human.epd -o src\evalparams.c" -f $Dest)
